version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 5173:5173
    volumes:
      - .:/home/node/app
    networks:
      - network-estagio-front

networks:
  network-estagio-front:
    driver: bridge
